/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MessDetectorPanel2.java
 *
 * Created on Nov 17, 2009, 1:45:25 PM
 */
package de.whitewashing.php.md.ui.options;

import java.io.File;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.filesystems.FileUtil;
import org.openide.util.NbBundle;

/**
 *
 * @author petr
 */
public class MessDetectorOptionsPanel extends javax.swing.JPanel
{

    /**
     * Suffix used for the last selected md directory.
     */
    private static final String MESS_DETECTOR_LAST_FOLDER_SUFFIX = ".messDetector";
    private MessDetectorOptions options = null;

    public MessDetectorOptionsPanel(MessDetectorOptions options)
    {
        this.options = options;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelStandard = new javax.swing.JLabel();
        messDetectorLabel = new javax.swing.JLabel();
        rulesetsTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        messDetectorTextField = new javax.swing.JTextField();

        setNextFocusableComponent(this);
        setPreferredSize(new java.awt.Dimension(612, 322));

        labelStandard.setText(org.openide.util.NbBundle.getMessage(MessDetectorOptionsPanel.class, "LBL_STANDARD")); // NOI18N

        messDetectorLabel.setText(org.openide.util.NbBundle.getMessage(MessDetectorOptionsPanel.class, "MessDetectorOptionsPanel.messDetectorLabel.text")); // NOI18N

        rulesetsTextField.setText(org.openide.util.NbBundle.getMessage(MessDetectorOptionsPanel.class, "MessDetectorOptionsPanel.messDetectorTextField.text")); // NOI18N

        browseButton.setText(org.openide.util.NbBundle.getMessage(MessDetectorOptionsPanel.class, "MessDetectorOptionsPanel.browseButton.text")); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        messDetectorTextField.setText(org.openide.util.NbBundle.getMessage(MessDetectorOptionsPanel.class, "MessDetectorOptionsPanel.messDetectorTextField.text")); // NOI18N
        messDetectorTextField.setName("messDetectorTextField"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(messDetectorLabel)
                    .add(labelStandard))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(messDetectorTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 365, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(browseButton))
                    .add(rulesetsTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 365, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(messDetectorLabel)
                    .add(browseButton)
                    .add(messDetectorTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelStandard)
                    .add(rulesetsTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(MessDetectorOptionsPanel.class, "MessDetectorOptionsPanel.AccessibleContext.accessibleDescription")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        File messDetectorScript = new FileChooserBuilder(MessDetectorOptionsPanel.class.getName() + MESS_DETECTOR_LAST_FOLDER_SUFFIX).setTitle(NbBundle.getMessage(MessDetectorOptionsPanel.class, "LBL_CodeSnifferSelect")).setFilesOnly(true).showOpenDialog();
        if (messDetectorScript != null) {
            messDetectorScript = FileUtil.normalizeFile(messDetectorScript);
            messDetectorTextField.setText(messDetectorScript.getAbsolutePath());
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    void load()
    {
        messDetectorTextField.setText(options.getRulesets());
        rulesetsTextField.setText(options.getShellScript());
    }

    void store()
    {
        // Only add when a standard exists
        options.setRulesets((String) rulesetsTextField.getText());
        options.setShellScript((String) messDetectorTextField.getText());
    }

    boolean valid()
    {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel labelStandard;
    private javax.swing.JLabel messDetectorLabel;
    private javax.swing.JTextField messDetectorTextField;
    private javax.swing.JTextField rulesetsTextField;
    // End of variables declaration//GEN-END:variables
}
